"""Step 9: minimal reproducible case of the Aidge 0.10.1 C++ int8 discrepancy (.venv-aidge).

Graph: a single 2D convolution (1 × 7) + ReLU, random input (1, C, 1, W).
The int8 convolution output is compared: quantized graph run in Python
(backend_cpu) against the C++ program generated by the export (per-layer output
recording, -DSAVE_OUTPUTS). Several sizes, to pin down the trigger.
The ONNX model is built directly with onnx (no dependency on PyTorch).
Run (from the repository root): .venv-aidge/bin/python step09_aidge_int8_case/minimal_case.py
"""
import glob
import re
import shutil
import subprocess
from pathlib import Path

import aidge_backend_cpu  # noqa: F401
import aidge_core
import aidge_onnx
import numpy as np
import onnx
from aidge_core.export_utils import export
from aidge_core.export_utils.config import ExportConfig
from aidge_core.export_utils.export import quantize_graph, quantize_inputs
from onnx import TensorProto, helper, numpy_helper

OUT = Path(__file__).resolve().parents[1] / "results" / "step09_aidge_int8_case"
aidge_core.Log.set_console_level(aidge_core.Level.Fatal)


def model(C, O, W, seed=0):
    rng = np.random.default_rng(seed)
    w = numpy_helper.from_array(rng.normal(0, 0.3, (O, C, 1, 7)).astype(np.float32), "w")
    b = numpy_helper.from_array(rng.normal(0, 0.1, O).astype(np.float32), "b")
    g = helper.make_graph(
        [helper.make_node("Conv", ["x", "w", "b"], ["c"], kernel_shape=[1, 7], pads=[0, 3, 0, 3]),
         helper.make_node("Relu", ["c"], ["y"])], "conv",
        [helper.make_tensor_value_info("x", TensorProto.FLOAT, [1, C, 1, W])],
        [helper.make_tensor_value_info("y", TensorProto.FLOAT, [1, O, 1, W])], [w, b])
    m = helper.make_model(g, opset_imports=[helper.make_opsetid("", 17)])
    m.ir_version = 8
    return m


def trial(C, O, W):
    name = f"C{C}_O{O}_W{W}"
    d = OUT / name
    shutil.rmtree(d, ignore_errors=True)
    d.mkdir(parents=True)
    onnx.save(model(C, O, W), d / "model.onnx")
    rng = np.random.default_rng(1)
    X = [rng.uniform(-0.8, 0.8, (1, C, 1, W)).astype(np.float32) for _ in range(16)]
    # Python: graph quantized by the same function as the export
    g = aidge_onnx.load_onnx(str(d / "model.onnx"))
    T = [aidge_core.Tensor(x) for x in X]
    g.set_backend("cpu")
    for t in T:
        t.to_backend("cpu")
    aidge_core.expand_metaops(g, name_format="{0}_{1}_{2}")
    quantize_graph(g, T)
    for n, i in g.get_ordered_inputs():
        if n.get_operator().get_input(i) is not None:
            n.get_operator().get_input(i).to_dtype(aidge_core.dtype.int8)
    g.set_backend("cpu")
    xq = np.array(quantize_inputs([aidge_core.Tensor(X[0])], "int8")[0])
    aidge_core.SequentialScheduler(g).forward(True, [aidge_core.Tensor(np.ascontiguousarray(xq))])
    n, i = g.get_ordered_outputs()[0]
    ref = np.array(n.get_operator().get_output(i)).reshape(O, W)
    # C++: int8 export, then compilation with output recording
    g2 = aidge_onnx.load_onnx(str(d / "model.onnx"))
    export(g2, ExportConfig(target="host", export_folder=str(d / "export"), dtype="int8", dformat="nchw"),
           input_tensors=[aidge_core.Tensor(x) for x in X], nb_test=0)
    e = d / "export"
    (e / "data" / "export_outputs").mkdir(parents=True, exist_ok=True)
    subprocess.run(["g++", "-O1", "-std=c++17", "-DSAVE_OUTPUTS", f"-I{e}", f"-I{e / 'dnn'}",
                    f"-I{e / 'dnn' / 'include'}", str(e / "main.cpp"), *glob.glob(str(e / "data" / "*.cpp")),
                    *[str(p) for p in (e / "dnn" / "src").rglob("*.cpp")], "-o", str(e / "run_debug")],
                   check=True, capture_output=True)
    subprocess.run([str(e / "run_debug")], cwd=e, capture_output=True)
    f = [p for p in glob.glob(str(e / "data" / "export_outputs" / "*.txt"))
         if "Transpose" not in p and ("Conv" in p or "ReLU" in p)]
    cpp = np.array([float(v) for v in re.findall(r"-?\d+\.?\d*", open(sorted(f)[-1]).read())]).reshape(O, W)
    diff = np.abs(cpp - ref)
    return name, float(diff.mean()), float(diff.max()), float(np.abs(ref).mean())


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    L = ["# Step 9: minimal case (one 1 × 7 convolution + ReLU, int8)", "",
         "Generated by `step09_aidge_int8_case/minimal_case.py`. Discrepancy between the int8 output of the C++ "
         "program generated by Aidge 0.10.1 and that of the same quantized graph run in Python (int8 scale, 0 to 127).", "",
         "| input (C channels, O outputs, W width) | mean deviation | max deviation | mean abs(output) |", "|---|---|---|---|"]
    for C, O, W in [(1, 4, 32), (4, 8, 32), (8, 8, 64), (8, 16, 128), (16, 8, 128), (66, 32, 128), (66, 32, 820),
                    (16, 16, 128), (16, 16, 820), (16, 32, 128), (32, 16, 128), (32, 32, 128), (48, 32, 128),
                    (64, 32, 128), (80, 32, 820)]:
        try:
            name, em, eM, am = trial(C, O, W)
            L.append(f"| {name} | {em:.2f} | {eM:.0f} | {am:.1f} |")
        except Exception as ex:
            L.append(f"| C{C}_O{O}_W{W} | failure: {type(ex).__name__} {str(ex)[:80]} | | |")
        print(L[-1], flush=True)
    L += ["", "Zero deviation exactly when C and O are both multiples of 16, in all sizes tested. Exact workaround "
          "applied to the CNN: input padded from 66 to 80 zero channels (zero weights), final layer from 1 to 16 "
          "outputs (logit = output 0); see `src/ogw/embedded.py`, `pad_channels`."]
    (OUT / "summary.md").write_text("\n".join(L) + "\n")
