"""Step 3: summary of the three methods (Step 2 baseline, supervised CNN, PCA).

Reads results/step02_baseline/metrics.json, results/step03_cnn_vs_pca/reports_*.json, pca_test.json
and the saved models; writes results/step03_cnn_vs_pca/summary.md and the figures.
Run (from the repository root, with PYTHONPATH=src): python step03_cnn_vs_pca/summary.py
"""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch

from ogw.anomaly import PCADetector
from ogw.splits import position_folds
from ogw.data import Normalizer, load_meta, load_signals
from ogw.training import predict
from ogw.models import CNN1D, n_mac, n_parameters

RES = Path(__file__).resolve().parents[1] / "results"
OUT = RES / "step03_cnn_vs_pca"
meta, X = load_meta(), load_signals()

ref = {r["split"]: r for r in json.loads((RES / "step02_baseline" / "metrics.json").read_text())
       if (r["choice"], r["aggregation"]) == ("optimal", "max")}
cnn = json.loads((OUT / "reports_test_default.json").read_text())
pca = {b["split"]: b for b in json.loads((OUT / "pca_test.json").read_text())}
val = {c: json.loads((OUT / f"reports_validation_{c}.json").read_text()) for c in ("default", "regularized")}
NAMES = ["position_D04", "position_D12", "position_D16", "position_D24", "temperature"]


def cnn_auc(name):
    return np.array([b["auc_test"] for b in cnn if b["split"] == name])


# --- Main table -------------------------------------------------------------------
L = ["# Step 3: supervised convolutional network versus anomaly detection (40 kHz)", "",
     "Generated by `step03_cnn_vs_pca/summary.py`. Test set opened only once per method, configuration "
     "frozen on the validation set. CNN: mean ± standard deviation over 5 seeds.", "",
     "## Test AUC", "",
     "| split | Step 2 baseline (no training) | supervised CNN | PCA, k = 5 (healthy only) |",
     "|---|---|---|---|"]
for n in NAMES:
    a = cnn_auc(n)
    L.append(f"| {n} | {ref[n]['auc']:.3f} | {a.mean():.3f} ± {a.std():.3f} (min {a.min():.3f}) "
             f"| {pca[n]['auc_test']:.3f} |")
d = cnn_auc("drift")
L += [f"| drift control (c1 versus c2) | not applicable | {d.mean():.3f} ± {d.std():.3f} | not applicable |",
      "", "## At the decision threshold calibrated without the test set", "",
      "| split | Step 2 baseline: FPR / TPR | PCA: FPR / TPR |", "|---|---|---|"]
for n in NAMES:
    L.append(f"| {n} | {ref[n]['fpr_threshold']:.3f} / {ref[n]['tpr_threshold']:.3f} "
             f"| {pca[n]['fpr_threshold']:.3f} / {pca[n]['tpr_threshold']:.3f} |")

# --- Costs ------------------------------------------------------------------
model = CNN1D()
n_lib, dim = 161, X.shape[1] * X.shape[2]
c_pca = pca["position_D04"]["cost"]
costs = [("Step 2 baseline (library of 161 measurements)", n_lib * dim, n_lib * dim),
         ("supervised CNN", n_parameters(model), n_mac(model, X.shape[1:])),
         ("PCA, k = 5", c_pca["values"], c_pca["mac"])]
L += ["", "## Cost per measurement (float32, before any compression)", "",
      "| method | stored values | memory | multiply-accumulates |", "|---|---|---|---|"]
for name, v, mac in costs:
    L.append(f"| {name} | {v:,} | {v * 4 / 1e6:.2f} MB | {mac / 1e6:.2f} M |")

# --- Validation history ------------------------------------------------
def nested_mean(c):
    return np.mean([b["auc_val"] for b in val[c] if b["split"].startswith("nested")])


L += ["", "## What the validation showed before the test", "",
      "- Original validation (38 to 42 °C band, positions already seen): AUC 1.000 on all "
      "splits, hence **saturated**, unusable for tuning anything.",
      "- Nested validation (one training position held out, the external test set left out): "
      "first version biased (healthy validation measurements all in a temperature band absent from "
      "training, hence AUCs inverted down to 0.06); corrected (healthy validation = "
      "cooling ramp of cycle 1, same temperatures as training).",
      f"- Corrected nested validation, mean AUC over 12 folds × 5 seeds: base configuration "
      f"{nested_mean('default'):.3f}, regularized configuration {nested_mean('regularized'):.3f}. "
      "Regularization does not help: base configuration kept.",
      "- PCA: k chosen per fold on the validation set (healthy measurements of the cooling ramp of cycle 1 + positions outside "
      "the test set); smallest k reaching the best AUC: k = 5 on all 4 folds."]

# --- CNN diagnosis on D16 and PCA false alarms ---------------------
dD16 = [x for x in position_folds(meta) if x.name == "position_D16"][0]
Xn = Normalizer().fit(X[dD16.train]).apply(X).astype(np.float32)
healthy1 = (meta.damaged == 0) & (meta.cycle == 1)
groups = {"healthy c1 (train)": np.flatnonzero(healthy1),
          "healthy c2 (test)": np.flatnonzero((meta.damaged == 0) & (meta.cycle == 2)),
          "D16 (test)": np.flatnonzero(meta.position == "D16"),
          "D04, D12, D24 (train)": np.flatnonzero((meta.damaged == 1) & (meta.position != "D16"))}
logits = {g: [] for g in groups}
for seed in range(5):
    m = CNN1D()
    m.load_state_dict(torch.load(OUT / "models" / f"cnn_position_D16_g{seed}.pt"))
    for g, idx in groups.items():
        logits[g].append(predict(m, Xn[idx]))
L += ["", "## Why the CNN AUC on D16 is below 0.5", "",
      "Median logit per group (5 seeds; > 0 means damaged): "
      + "; ".join(f"{g} {np.median(np.concatenate(v)):+.1f}" for g, v in logits.items()) + ".",
      "The network clearly classifies D16 as healthy: it recognizes the positions it has seen, not damage in "
      "general. The AUC below 0.5 only reflects small differences within the healthy class."]

det = PCADetector(5).fit(X, np.flatnonzero(healthy1 & (meta.ramp == 0)), np.flatnonzero(healthy1 & (meta.ramp == 1)))
s2 = groups["healthy c2 (test)"]
fa = s2[det.scores(s2) > det.threshold]
L += ["", "## PCA false alarms (position splits)", "",
      f"{len(fa)} out of 161, all between {meta.T_measured[fa].min():.1f} and {meta.T_measured[fa].max():.1f} °C: "
      f"cold end, at the edge of the learned domain (the heating ramp of cycle 1 starts at "
      f"{meta.T_measured[np.flatnonzero(healthy1 & (meta.ramp == 0))].min():.1f} °C)."]
(OUT / "summary.md").write_text("\n".join(L) + "\n")
print("\n".join(L))

# --- Figures ------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 3.8))
xs = np.arange(len(NAMES))
ax.plot(xs - 0.2, [ref[n]["auc"] for n in NAMES], "s", color="0.4", ms=8, label="Step 2 baseline")
for k, n in enumerate(NAMES):
    a = cnn_auc(n)
    ax.plot(np.full(len(a), k), a, "o", color="C3", alpha=0.5, ms=5, label="supervised CNN (seeds)" if k == 0 else None)
    ax.plot(k, a.mean(), "_", color="C3", ms=18, mew=2)
ax.plot(xs + 0.2, [pca[n]["auc_test"] for n in NAMES], "D", color="C2", ms=7, label="PCA, k = 5")
ax.axhline(0.5, color="k", ls=":", lw=0.8)
ax.set_xticks(xs, [n.replace("position_", "position\n") for n in NAMES])
ax.set_ylabel("test AUC"); ax.set_ylim(0, 1.05); ax.legend(fontsize=8, loc="lower left")
ax.set_title("Damage at a position never seen: the supervised CNN fails, PCA does not")
fig.tight_layout(); fig.savefig(OUT / "01_auc_comparison.png", dpi=110); plt.close(fig)

fig, ax = plt.subplots(figsize=(7, 3.6))
for k, (g, v) in enumerate(logits.items()):
    ax.boxplot(np.concatenate(v), positions=[k], widths=0.5, showfliers=False)
ax.axhline(0, color="C3", ls="--", lw=0.8)
ax.set_xticks(range(len(logits)), list(logits), fontsize=8); ax.set_ylabel("CNN logit")
ax.set_title("D16 fold: the CNN classifies the unknown damage as healthy")
fig.tight_layout(); fig.savefig(OUT / "02_cnn_logits_D16.png", dpi=110); plt.close(fig)

fig, ax = plt.subplots(figsize=(8, 3.6))
for idx, c, leg in ((s2, "k", "healthy c2 (test)"),
                    *[(np.flatnonzero(meta.position == p), f"C{k}", p) for k, p in enumerate(["D04", "D12", "D16", "D24"])]):
    ax.semilogy(meta.T_measured[idx], det.scores(idx), ".", ms=3, color=c, label=leg)
ax.axhline(det.threshold, color="C9", ls="--", label="calibrated threshold")
ax.set_xlabel("measured T (°C)"); ax.set_ylabel("PCA indicator")
ax.set_title(f"PCA (k = 5, learned on {det.n_train} healthy measurements): indicator vs temperature")
ax.legend(fontsize=7, ncol=3)
fig.tight_layout(); fig.savefig(OUT / "03_pca_indicator_vs_temperature.png", dpi=110); plt.close(fig)

fig, axs = plt.subplots(1, 2, figsize=(10, 3.4), sharey=True)
for ax, name in zip(axs, ["position_D04", "position_D16"]):
    for b in [b for b in cnn if b["split"] == name]:
        h = b["history"]
        ax.semilogy([e["train_loss"] for e in h], color="C0", lw=0.8)
        ax.semilogy([e["val_loss"] for e in h], color="C1", lw=0.8)
    ax.set_title(f"CNN, {name} (5 seeds)"); ax.set_xlabel("epoch")
axs[0].plot([], [], color="C0", label="training"); axs[0].plot([], [], color="C1", label="validation")
axs[0].set_ylabel("loss"); axs[0].legend(fontsize=8)
fig.tight_layout(); fig.savefig(OUT / "04_cnn_curves.png", dpi=110); plt.close(fig)
