"""Step 2: evaluation of the baseline indicator (no training).

Main variant fixed before looking at the test set: optimal baseline (minimal
residual), maximum over the paths. The other variants are comparisons, not a
selection.

For each split: library = healthy measurements outside the test set; threshold
calibrated on the library alone (95 % quantile); metrics on the test set.
Run (from the repository root): PYTHONPATH=src python step02_baseline/evaluate_baseline.py
"""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve

from ogw.baseline import AGGREGATIONS, CHOICES, BaselineIndicator
from ogw.data import load_meta, load_signals
from ogw.splits import TEST_BAND, by_temperature, check, position_folds

OUT = Path(__file__).resolve().parents[1] / "results" / "step02_baseline"
OUT.mkdir(parents=True, exist_ok=True)
MAIN = ("optimal", "max")
rng = np.random.default_rng(0)

meta = load_meta()
X = load_signals()
splits = [*position_folds(meta), by_temperature(meta)]


def tpr_at_fpr(y, s, target_fpr=0.05):
    fpr, tpr, _ = roc_curve(y, s)
    return float(np.interp(target_fpr, fpr, tpr))


def auc_interval(y, s, n=1000):
    """95 % bootstrap interval (optimistic: neighbouring measurements are correlated)."""
    v = []
    for _ in range(n):
        k = rng.integers(0, len(y), len(y))
        if 0 < y[k].sum() < len(k):
            v.append(roc_auc_score(y[k], s[k]))
    return np.percentile(v, [2.5, 97.5]).tolist()


results, outputs = [], {}
for d in splits:
    check(d, meta)
    lib = np.flatnonzero(meta.damaged == 0)
    lib = np.intersect1d(lib, np.r_[d.train, d.validation])
    y = d.target[d.test]
    for choice in CHOICES:
        for aggregation in AGGREGATIONS:
            ind = BaselineIndicator(choice, aggregation).fit(X, meta, lib)
            s = ind.scores(d.test)
            pred = s > ind.threshold
            r = dict(split=d.name, choice=choice, aggregation=aggregation,
                     auc=float(roc_auc_score(y, s)), tpr_fpr5=tpr_at_fpr(y, s),
                     threshold=float(ind.threshold), fpr_threshold=float(pred[y == 0].mean()),
                     tpr_threshold=float(pred[y == 1].mean()), n_test=int(len(y)),
                     n_library=int(len(lib)))
            if (choice, aggregation) == MAIN:
                r["auc_ci95"] = auc_interval(y, s)
                outputs[d.name] = dict(scores=s, y=y, threshold=ind.threshold, T=meta.T_measured[d.test],
                                       residuals=ind.residuals(d.test))
            results.append(r)
            print(f"{d.name:16s} {choice:9s} {aggregation:8s} AUC {r['auc']:.3f} "
                  f"TPR@5% {r['tpr_fpr5']:.3f} | calibrated threshold: FPR {r['fpr_threshold']:.3f} TPR {r['tpr_threshold']:.3f}")

(OUT / "metrics.json").write_text(json.dumps(results, indent=1, ensure_ascii=False))

# --- Tables -------------------------------------------------------------------
L = ["# Step 2: baseline indicator without training (40 kHz)", "",
     "Generated by `step02_baseline/evaluate_baseline.py`. Main variant fixed a priori: "
     "**optimal baseline, maximum over the paths**. Threshold calibrated on the healthy "
     "library alone (95 % quantile, target false alarm rate: 5 %).", "",
     "## Main variant", "",
     "| split | AUC | 95 % CI (bootstrap) | TPR at FPR 5 % | calibrated threshold: FPR | calibrated threshold: TPR |",
     "|---|---|---|---|---|---|"]
for r in results:
    if (r["choice"], r["aggregation"]) == MAIN:
        a, b = r["auc_ci95"]
        L.append(f"| {r['split']} | {r['auc']:.3f} | [{a:.3f}, {b:.3f}] | {r['tpr_fpr5']:.3f} "
                 f"| {r['fpr_threshold']:.3f} | {r['tpr_threshold']:.3f} |")
L += ["", "The bootstrap interval assumes independent measurements; measurements close in "
      "temperature are correlated, so it is optimistic.", "",
      "## Variant comparison (AUC)", "",
      "| baseline | aggregation | " + " | ".join(d.name for d in splits) + " |",
      "|---|---|" + "---|" * len(splits)]
for choice in CHOICES:
    for aggregation in AGGREGATIONS:
        L.append(f"| {choice} | {aggregation} | " + " | ".join(
            f"{r['auc']:.3f}" for r in results if r["choice"] == choice and r["aggregation"] == aggregation) + " |")

# Where are the errors? (main variant, position splits)
L += ["", "## Errors of the main variant at the calibrated threshold (position splits)", ""]
for name, o in outputs.items():
    if not name.startswith("position"):
        continue
    fa = o["T"][(o["y"] == 0) & (o["scores"] > o["threshold"])]
    nd = o["T"][(o["y"] == 1) & (o["scores"] <= o["threshold"])]
    L.append(f"- {name}: {len(fa)} false alarms out of 161"
             + (f" (T from {fa.min():.1f} to {fa.max():.1f} °C)" if len(fa) else "")
             + f", {len(nd)} missed damages out of 161"
             + (f" (T from {nd.min():.1f} to {nd.max():.1f} °C)" if len(nd) else "") + ".")

o = outputs["temperature"]
inside = (o["T"] >= TEST_BAND[0]) & (o["T"] <= TEST_BAND[1])
L += ["", f"Temperature split: the test set ({TEST_BAND[0]:.0f} to {TEST_BAND[1]:.0f} °C) has no "
      f"healthy baseline within its range; median indicator of the healthy test measurements "
      f"{np.median(o['scores'][o['y'] == 0]):.1f}, for a threshold of {o['threshold']:.1f}."]
# Quality check and embedded cost
lib1 = np.flatnonzero((meta.damaged == 0) & (meta.cycle == 1))
ind = BaselineIndicator().fit(X, meta, lib1)
dp = np.argwhere(ind.faulty)
L += ["", "## Acquisition quality check", "",
      f"{len(dp)} (measurement, path) pairs nearly empty (energy < 30 % of the path median), "
      "all on path " + ", ".join(sorted({f"{meta.paths[t][0]}-{meta.paths[t][1]}" for _, t in dp}))
      + ": " + ", ".join(f"{i} ({meta.label[i]}, c{meta.cycle[i]})" for i, _ in dp) + ".",
      "These paths are excluded from the indicator (sensor failure, not damage). **Record:** the "
      "check was added after examining the false alarms of the test set (measurements 296 and 298 of "
      "healthy cycle 2); the same fault exists in the training data (healthy cycle 1), so a quality "
      "check run on the training data alone would also have revealed it.",
      "", "## Cost of the method for embedded use", ""]
n_lib, n_val = len(lib1), X.shape[1] * X.shape[2]
L += [f"- Memory: library of {n_lib} measurements × {X.shape[1]} paths × {X.shape[2]} points "
      f"= {n_lib * n_val / 1e6:.1f} million values, i.e. {n_lib * n_val * 4 / 1e6:.1f} MB in float32.",
      f"- Computation per evaluated measurement: {n_lib} distances of dimension {n_val}, i.e. "
      f"{n_lib * n_val / 1e6:.1f} million multiply-accumulates.",
      "- Coverage: a healthy baseline is needed at every temperature encountered "
      "(see the temperature split)."]
(OUT / "summary.md").write_text("\n".join(L) + "\n")
print("\n".join(L))

# --- Figures ------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(5, 4.5))
for name, o in outputs.items():
    fpr, tpr, _ = roc_curve(o["y"], o["scores"])
    ax.plot(fpr, tpr, label=f"{name} (AUC {roc_auc_score(o['y'], o['scores']):.3f})")
ax.plot([0, 1], [0, 1], "k:", lw=0.8)
ax.set_xlabel("false alarm rate"); ax.set_ylabel("detection rate")
ax.set_title("ROC curves: optimal baseline, max"); ax.legend(fontsize=7)
fig.tight_layout(); fig.savefig(OUT / "01_roc.png", dpi=110); plt.close(fig)

fig, axs = plt.subplots(1, 5, figsize=(17, 3.6), sharey=True)
for ax, (name, o) in zip(axs, outputs.items()):
    for cl, c, leg in ((0, "k", "healthy (test)"), (1, "C3", "damaged (test)")):
        m = o["y"] == cl
        ax.semilogy(o["T"][m], o["scores"][m], ".", ms=3, color=c, label=leg)
    ax.axhline(o["threshold"], color="C0", ls="--", label="calibrated threshold")
    ax.set_title(name, fontsize=9); ax.set_xlabel("measured T (°C)")
axs[0].set_ylabel("indicator (max of normalized residuals)"); axs[0].legend(fontsize=7)
fig.tight_layout(); fig.savefig(OUT / "02_indicator_vs_temperature.png", dpi=110); plt.close(fig)
