"""Step 6: damage localization on the 644 damaged measurements (40 kHz).

Parameters fixed before the evaluation, without using any damage position:
- PCA detector (k = 5) from Step 3: heating ramp of healthy cycle 1 (fit),
  cooling ramp of healthy cycle 1 (healthy levels);
- RAPID: beta = 1.05, per-path index = normalized residual minus 1;
- delay and sum: v and t0 calibrated on the direct arrivals of the heating ramp
  of healthy cycle 1; envelopes of the PCA residuals divided by the healthy RMS
  residual level of each path (cooling ramp of healthy cycle 1).
Supervised comparison: regression (ridge, multilayer perceptron) of the
coordinates from the 66 normalized residuals, trained on 3 positions and
evaluated on the 4th (no test position seen).
Run (from the repository root): .venv/bin/python step06_localization/localize.py
"""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import hilbert
from sklearn.linear_model import RidgeCV
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from ogw.anomaly import PCADetector
from ogw.splits import POSITIONS
from ogw.data import Q, load_meta, load_signals
from ogw.localization import (DEFECTS, RAPID, TRANSDUCERS, DelayAndSum, calibrate_velocity, error,
                              damage_index)

OUT = Path(__file__).resolve().parents[1] / "results" / "step06_localization"
OUT.mkdir(parents=True, exist_ok=True)
meta, X = load_meta(), load_signals()
fs = meta.fs / Q
healthy1 = (meta.damaged == 0) & (meta.cycle == 1)
train, val = np.flatnonzero(healthy1 & (meta.ramp == 0)), np.flatnonzero(healthy1 & (meta.ramp == 1))
det = PCADetector(5).fit(X, train, val)

# --- Calibrations (healthy measurements only) ------------------------------------
v, t0, rms_t = calibrate_velocity(X[train].astype(np.float64), meta.paths, fs)
level = np.sqrt((det.residual_signals(val) ** 2).mean(axis=(0, 2)))              # (66,)
rapid = RAPID(meta.paths, beta=1.05)
das = DelayAndSum(meta.paths, v, t0, fs, X.shape[-1])

# --- Localization ------------------------------------------------------------------
res, est, di_per_pos = {}, {}, {}
for p in POSITIONS:
    idx = np.flatnonzero(meta.position == p)
    di = damage_index(det.residuals(idx))
    env = np.abs(hilbert(det.residual_signals(idx), axis=-1)) / level[None, :, None]
    di_per_pos[p] = det.residuals(idx)
    est[p] = {"RAPID": rapid.localize(di), "delay and sum": das.localize(env)}
    res[p] = {m: error(e, DEFECTS[p]) for m, e in est[p].items()}

# --- Supervised comparison: one position left out -----------------------------------
models = {"ridge": lambda: make_pipeline(StandardScaler(), RidgeCV(alphas=np.logspace(-3, 3, 13))),
          "multilayer perceptron": lambda: make_pipeline(StandardScaler(), MLPRegressor(
              hidden_layer_sizes=(64, 64), max_iter=2000, random_state=0))}
for p in POSITIONS:
    others = [q for q in POSITIONS if q != p]
    Xa = np.log(np.nan_to_num(np.concatenate([di_per_pos[q] for q in others]), nan=1.0) + 1e-3)
    ya = np.concatenate([np.tile(DEFECTS[q], (len(di_per_pos[q]), 1)) for q in others])
    Xt = np.log(np.nan_to_num(di_per_pos[p], nan=1.0) + 1e-3)
    for name, factory in models.items():
        m = factory().fit(Xa, ya)
        est[p][f"{name} (supervised)"] = m.predict(Xt)
        res[p][f"{name} (supervised)"] = error(est[p][f"{name} (supervised)"], DEFECTS[p])

methods = list(res[POSITIONS[0]])
L = ["# Step 6: damage localization (40 kHz, 644 damaged measurements)", "",
     "Generated by `step06_localization/localize.py`. Parameters fixed before the evaluation, without any "
     f"damage position: PCA k = 5; RAPID β = 1.05; delay and sum with v = {v:.3f} mm/µs and t0 = {t0:.1f} µs "
     f"calibrated on the healthy direct arrivals (RMS deviation {rms_t:.1f} µs). Supervised methods: "
     "trained on 3 positions, evaluated on the 4th.", "",
     "## Localization error (mm): median [90th percentile]", "",
     "| method | " + " | ".join(POSITIONS) + " | all |", "|---" * (len(POSITIONS) + 2) + "|"]
for m in methods:
    everything = np.concatenate([res[p][m] for p in POSITIONS])
    L.append(f"| {m} | " + " | ".join(f"{np.median(res[p][m]):.0f} [{np.percentile(res[p][m], 90):.0f}]"
                                      for p in POSITIONS)
             + f" | {np.median(everything):.0f} [{np.percentile(everything, 90):.0f}] |")
L += ["", "## Share of measurements localized within 25 mm / 50 mm", "",
      "| method | " + " | ".join(POSITIONS) + " |", "|---" * (len(POSITIONS) + 1) + "|"]
for m in methods:
    L.append(f"| {m} | " + " | ".join(f"{(res[p][m] < 25).mean():.0%} / {(res[p][m] < 50).mean():.0%}"
                                      for p in POSITIONS) + " |")
# --- Sensitivity to velocity (post hoc analysis: not used to choose v) --------------
L += ["", "## Sensitivity of delay and sum to velocity (post hoc analysis, not a tuning step)", "",
      "| factor on v | " + " | ".join(POSITIONS) + " | all |", "|---" * (len(POSITIONS) + 2) + "|"]
env_pos = {p: np.abs(hilbert(det.residual_signals(np.flatnonzero(meta.position == p)), axis=-1))
           / level[None, :, None] for p in POSITIONS}
for f in (0.95, 1.0, 1.05, 1.10):
    das_f = DelayAndSum(meta.paths, v * f, t0, fs, X.shape[-1])
    e = {p: error(das_f.localize(env_pos[p]), DEFECTS[p]) for p in POSITIONS}
    L.append(f"| {f:.2f} | " + " | ".join(f"{np.median(e[p]):.0f}" for p in POSITIONS)
             + f" | {np.median(np.concatenate(list(e.values()))):.0f} |")
(OUT / "summary.md").write_text("\n".join(L) + "\n")
(OUT / "measurements.json").write_text(json.dumps(
    dict(v_mm_us=v, t0_us=t0, rms_us=rms_t,
         errors={p: {m: e.tolist() for m, e in r.items()} for p, r in res.items()}), ensure_ascii=False))
print("\n".join(L))

# --- Figures -------------------------------------------------------------------------
fig, axs = plt.subplots(1, 2, figsize=(11, 5.2))
for ax, m in zip(axs, ["RAPID", "delay and sum"]):
    for k, p in enumerate(POSITIONS):
        ax.plot(*est[p][m].T, ".", ms=3, color=f"C{k}", alpha=0.4)
        ax.plot(*DEFECTS[p], "X", ms=12, color=f"C{k}", mec="k", label=f"{p} (true position)")
    ax.plot(*TRANSDUCERS.T, "ks", ms=6, label="transducers")
    ax.set_xlim(0, 500); ax.set_ylim(0, 500); ax.set_aspect("equal"); ax.set_title(m)
    ax.set_xlabel("x (mm)")
axs[0].set_ylabel("y (mm)"); axs[1].legend(fontsize=7, loc="center left")
fig.suptitle("Estimated positions on the 644 damaged measurements (dots) and true positions (crosses)")
fig.tight_layout(); fig.savefig(OUT / "01_estimated_positions.png", dpi=110); plt.close(fig)

fig, axs = plt.subplots(2, 4, figsize=(15, 7.5))
for k, p in enumerate(POSITIONS):
    i = np.flatnonzero(meta.position == p)[40]                        # one measurement, around 40 °C, heating ramp
    di = damage_index(det.residuals([i]))[0]
    env = np.abs(hilbert(det.residual_signals([i]), axis=-1))[0] / level[:, None]
    for ax, c, m in ((axs[0, k], rapid.map(di), "RAPID"), (axs[1, k], das.map(env), "delay and sum")):
        ax.imshow(c, origin="lower", extent=(0, 500, 0, 500), cmap="magma")
        ax.plot(*TRANSDUCERS.T, "ws", ms=4); ax.plot(*DEFECTS[p], "cX", ms=10, mec="k")
        ax.set_title(f"{p}, {m} ({meta.T_measured[i]:.0f} °C)", fontsize=9); ax.set_xticks([]); ax.set_yticks([])
fig.tight_layout(); fig.savefig(OUT / "02_maps.png", dpi=110); plt.close(fig)
