"""Step 5: locate the failure of Aidge 0.10.1 int8 (.venv-aidge environment).

1. Does the 2D CNN graph quantized by Aidge (same function as the export) work
   in Python (backend_cpu)?  -> correlation with the ONNX Runtime float model.
2. Does the C++ program generated by the export (its own main, its own embedded
   input) give the same result?  -> output for measurement calib[0].
3. Does per-channel quantization (channel_wise=True) complete?  -> run in
   a subprocess, since it can crash the interpreter.
Prerequisite: step05_aidge_export/export_aidge.py already run.
Run (from the repository root): .venv-aidge/bin/python step05_aidge_export/diagnostic_int8.py
"""
import subprocess
import sys
from pathlib import Path

import aidge_backend_cpu  # noqa: F401
import aidge_core
import aidge_onnx
import numpy as np
from aidge_core.export_utils.export import quantize_graph, quantize_inputs

R = Path(__file__).resolve().parents[1]
S5 = R / "results" / "step05_aidge_export"
aidge_core.Log.set_console_level(aidge_core.Level.Fatal)
D = np.load(R / "data" / "step05_inputs.npz")
SHAPE = (1, 66, 1, 820)


def run(g, X):
    sch, out = aidge_core.SequentialScheduler(g), []
    for x in X:
        sch.forward(True, [aidge_core.Tensor(np.ascontiguousarray(x))])
        n, i = g.get_ordered_outputs()[0]
        out.append(float(np.array(n.get_operator().get_output(i)).ravel()[0]))
    return np.array(out)


lines = ["", "## int8 diagnostic (generated by `step05_aidge_export/diagnostic_int8.py`)", ""]
g = aidge_onnx.load_onnx(str(S5 / "cnn_folded_2d.onnx"))
calib = [aidge_core.Tensor(np.ascontiguousarray(x.reshape(SHAPE))) for x in D["calib"]]
g.set_backend("cpu")
for t in calib:
    t.to_backend("cpu")
aidge_core.expand_metaops(g, name_format="{0}_{1}_{2}")
quantize_graph(g, calib)
for n, i in g.get_ordered_inputs():
    if n.get_operator().get_input(i) is not None:
        n.get_operator().get_input(i).to_dtype(aidge_core.dtype.int8)
g.set_backend("cpu")
Xq = [np.array(t) for t in quantize_inputs(
    [aidge_core.Tensor(np.ascontiguousarray(x.reshape(SHAPE))) for x in D["test"]], "int8")]
s = run(g, Xq)
c = np.corrcoef(s, D["ort_cnn_folded"])[0, 1]
lines.append(f"1. Graph quantized by Aidge, run in Python (backend_cpu): correlation {c:.3f} with the "
             f"float model; output ≈ {np.median(s / D['ort_cnn_folded']):.1f} × logit. **Quantization works.**")

r = subprocess.run(["./build/run_export"], cwd=S5 / "exports" / "cnn2d_int8_nchw", capture_output=True, text=True)
cpp_output = r.stdout.split("\n")[1].strip()
lines.append(f"2. Generated C++ program (its own main, its own embedded input, measurement calib[0] "
             f"with float logit -10.31): output **{cpp_output}**. The int8 C++ generation collapses the output; "
             "the test harness is not at fault (same input, same output).")

code = subprocess.run([sys.executable, "-c", f"""
import aidge_core, aidge_onnx, aidge_backend_cpu, aidge_quantization as aq, numpy as np
aidge_core.Log.set_console_level(aidge_core.Level.Fatal)
D = np.load('{R / "data" / "step05_inputs.npz"}')
g = aidge_onnx.load_onnx('{S5 / "cnn_folded_2d.onnx"}')
T = [aidge_core.Tensor(np.ascontiguousarray(x.reshape({SHAPE}))) for x in D['calib'][:32]]
g.set_backend('cpu'); [t.to_backend('cpu') for t in T]
aidge_core.expand_metaops(g, name_format='{{0}}_{{1}}_{{2}}')
aq.auto_assign_node_precision(graphview=g, act_precision=aidge_core.dtype.int8,
    weight_precision=aidge_core.dtype.int8, bias_precision=aidge_core.dtype.int32)
aq.quantize_network(network=g, calibration_set=T, channel_wise=True)
"""], capture_output=True).returncode
lines.append(f"3. Per-channel quantization (`channel_wise=True`): return code {code}"
             + (" (**segmentation fault**)." if code in (-11, 139) else "."))

with open(S5 / "summary.md", "a") as f:
    f.write("\n".join(lines) + "\n")
print("\n".join(lines))
