"""Step 5: C++ export with Eclipse Aidge 0.10.1 (.venv-aidge environment).

For each configuration (ONNX model, dtype, data format), the C++ code is
generated with aidge_core.export_utils.export, a test program (harness) is
compiled against the generated model_forward function, run on 64 test
measurements and 128 calibration measurements, and compared with ONNX Runtime.
Failing configurations are kept: they are part of the findings.

Prerequisite: .venv/bin/python step05_aidge_export/prepare_data.py (data and folded ONNX models).
Run (from the repository root): .venv-aidge/bin/python step05_aidge_export/export_aidge.py
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import aidge_backend_cpu  # noqa: F401  (registers the CPU backend)
import aidge_core
import aidge_onnx
import aidge_quantization as aq
import numpy as np
from aidge_core.export_utils import export
from aidge_core.export_utils.config import ExportConfig
from sklearn.metrics import roc_auc_score

R = Path(__file__).resolve().parents[1]
OUT = R / "results" / "step05_aidge_export"
aidge_core.Log.set_console_level(aidge_core.Level.Fatal)
D = np.load(R / "data" / "step05_inputs.npz")
X = np.concatenate([D["test"], D["calib"]]).astype(np.float32)    # 64 test then 128 calibration


def pad(A, name):
    """Variants "_16": input padded with zero channels up to 80 (Step 9)."""
    return np.concatenate([A, np.zeros((len(A), 80 - A.shape[1], A.shape[2]), A.dtype)], 1) if "_16" in name else A
NT = len(D["test"])
SIZES = {"float": 4, "int8_t": 1, "uint8_t": 1, "int16_t": 2, "int32_t": 4, "int64_t": 8, "bool": 1}

CONFIGS = [  # name, ONNX file, dtype, format, note[, manual quantization options]
    ("cnn1d_f32_auto", OUT / "cnn_folded.onnx", "float32", None, "format chosen automatically"),
    ("cnn1d_f32_ncw", OUT / "cnn_folded.onnx", "float32", "ncw", ""),
    ("cnn1d_int8_ncw", OUT / "cnn_folded.onnx", "int8", "ncw", "MaxPooling1D not quantizable"),
    ("cnn2d_f32", OUT / "cnn_folded_2d.onnx", "float32", None, "exact 2D rewrite"),
    ("cnn2d_int8", OUT / "cnn_folded_2d.onnx", "int8", None, "2D rewrite, Aidge quantization"),
    ("cnn2d_f32_nchw", OUT / "cnn_folded_2d.onnx", "float32", "nchw", ""),
    ("cnn2d_int8_nchw", OUT / "cnn_folded_2d.onnx", "int8", "nchw", "default quantization of the export"),
    # channel_wise=True crashes quantize_network (segmentation fault, checked separately):
    # only per-tensor variants are tried
    ("cnn2d_int8_nchw_mse", OUT / "cnn_folded_2d.onnx", "int8", "nchw",
     "per tensor, MSE clipping, no powers of 2",
     dict(clipping_mode=aq.Clipping.MSE, channel_wise=False, single_shift=False)),
    ("cnn2d_int8_nchw_max", OUT / "cnn_folded_2d.onnx", "int8", "nchw",
     "per tensor, MAX clipping, no powers of 2",
     dict(clipping_mode=aq.Clipping.MAX, channel_wise=False, single_shift=False)),
    # Step 9: global maximum as a cascade of small MaxPool (1, 2), (1, 3), (1, 17), identical result
    ("cnn2d_cascade_f32_nchw", OUT / "cnn_folded_2d_cascade.onnx", "float32", "nchw", "cascaded global max"),
    ("cnn2d_cascade_int8_nchw", OUT / "cnn_folded_2d_cascade.onnx", "int8", "nchw", "cascaded global max"),
    ("cnn2d_small_int8_nchw", OUT / "cnn_folded_2d_small.onnx", "int8", "nchw",
     "zero padding (102 -> 108), poolings of width 2 and 3 only"),
    ("cnn2d_16_f32_nchw", OUT / "cnn_folded_2d_16.onnx", "float32", "nchw",
     "channels padded to multiples of 16 (input 66 -> 80)"),
    ("cnn2d_16_int8_nchw", OUT / "cnn_folded_2d_16.onnx", "int8", "nchw",
     "channels padded to multiples of 16 (input 66 -> 80)"),
    ("pca_f32_ncw", R / "results" / "step04_embedded_export" / "onnx" / "pca_position.onnx", "float32", "ncw", ""),
    ("pca_int8_weights_ncw", R / "results" / "step04_embedded_export" / "onnx" / "pca_position_int8_weights.onnx",
     "float32", "ncw", "int8 weights already in the graph"),
    ("pca_nc_f32_ncw", OUT / "pca_no_check.onnx", "float32", "ncw", "quality check outside the graph"),
    ("pca_nc_int8_weights_ncw", OUT / "pca_no_check_int8_weights.onnx", "float32", "ncw",
     "quality check outside the graph"),
]

HARNESS = r"""#include <algorithm>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include "forward.hpp"

// Test harness generated by step05_aidge_export/export_aidge.py: reads N binary inputs,
// writes the first output of each inference, then measures the latency on input 0.
int main(int argc, char** argv) {
    const size_t D = @D@;
    const int N = atoi(argv[2]);
    std::vector<@T@> x((size_t)N * D);
    FILE* f = fopen(argv[1], "rb");
    if (!f || fread(x.data(), sizeof(@T@), x.size(), f) != x.size()) return 2;
    fclose(f);
    @DECL@
    FILE* o = fopen(argv[3], "w");
    for (int i = 0; i < N; ++i) {
        model_forward(&x[(size_t)i * D], @ARGS@);
        fprintf(o, "%.9g\n", (double)s0[0]);
    }
    fclose(o);
    std::vector<double> t;
    for (int k = 0; k < 1030; ++k) {
        auto a = std::chrono::steady_clock::now();
        model_forward(&x[0], @ARGS@);
        auto b = std::chrono::steady_clock::now();
        if (k >= 30) t.push_back(std::chrono::duration<double, std::milli>(b - a).count());
    }
    std::sort(t.begin(), t.end());
    printf("%.4f %.4f\n", t[t.size() / 2], t[(size_t)(0.95 * t.size())]);
    return 0;
}
"""


def quantize_manually(g, tensors, options):
    """Same steps as the internal quantization of the Aidge export, with chosen options."""
    from aidge_core.export_utils.export import quantize_inputs, remove_concat_quantizers
    g.set_backend("cpu")
    for t in tensors:
        t.to_backend("cpu")
    aidge_core.expand_metaops(g, name_format="{0}_{1}_{2}")
    aq.auto_assign_node_precision(graphview=g, act_precision=aidge_core.dtype.int8,
                                  weight_precision=aidge_core.dtype.int8, bias_precision=aidge_core.dtype.int32)
    aq.quantize_network(network=g, calibration_set=tensors, **options)
    for n, i in g.get_ordered_inputs():
        if n.get_operator().get_input(i) is not None:
            n.get_operator().get_input(i).to_dtype(aidge_core.dtype.int8)
    remove_concat_quantizers(g)
    return quantize_inputs(tensors, "int8")


def generate(name, onnx, dtype, dformat, options=None):
    folder = OUT / "exports" / name
    shutil.rmtree(folder, ignore_errors=True)
    g = aidge_onnx.load_onnx(str(onnx))
    quantizable = bool(aq.check_architecture(g)) if dtype == "int8" else None
    inputs = pad(D["calib"] if dtype == "int8" else D["calib"][:1], name)
    c = inputs.shape[1]
    shape = (1, c, 1, 820) if "2d" in name else (1, c, 820)          # 2D CNN: height 1
    tensors = [aidge_core.Tensor(np.ascontiguousarray(x.reshape(shape))) for x in inputs]
    if options is not None:
        tensors = quantize_manually(g, tensors, options)
    export(g, ExportConfig(target="host", export_folder=str(folder), dtype=dtype, dformat=dformat,
                           model_prequantized=options is not None),
           input_tensors=tensors, nb_test=0)
    return folder, quantizable


def compile_harness(folder):
    fwd = (folder / "dnn" / "include" / "forward.hpp").read_text()
    params = [p.strip() for p in re.search(r"model_forward\s*\((.*?)\);", fwd, re.S).group(1).split(",")]
    t_input = params[0].replace("const", "").split("*")[0].strip()
    t_outputs = [p.split("*")[0].strip() for p in params[1:]]
    decl = " ".join(f"{t}* s{k} = nullptr;" for k, t in enumerate(t_outputs))
    args = ", ".join(f"&s{k}" for k in range(len(t_outputs)))
    n = int(np.prod(pad(D["test"][:1], folder.name).shape[1:]))
    src = (HARNESS.replace("@D@", str(n)).replace("@T@", t_input)
           .replace("@DECL@", decl).replace("@ARGS@", args))
    (folder / "harness.cpp").write_text(src)
    sources = [str(p) for p in (folder / "dnn" / "src").rglob("*.cpp")]
    exe = folder / "harness"
    subprocess.run(["g++", "-O3", "-ffast-math", "-march=native", "-std=c++17", f"-I{folder}",
                    f"-I{folder / 'dnn'}", f"-I{folder / 'dnn' / 'include'}", str(folder / "harness.cpp"),
                    *sources, "-o", str(exe)], check=True, capture_output=True)
    return exe, t_input


def memory(folder):
    """Bytes of the compute arena and of the parameters declared in the generated code."""
    fwd = (folder / "dnn" / "src" / "forward.cpp").read_text()
    arena = sum(int(v) for v in re.findall(r"static unsigned char mem_\d+\[(\d+)\]", fwd))
    param = 0
    for p in (folder / "dnn" / "src" / "parameters").glob("*.cpp"):
        for t, dims in re.findall(r"const (\w+) \w+\[([\d\*]+)\]", p.read_text()):
            param += SIZES.get(t, 4) * int(np.prod([int(v) for v in dims.split("*")]))
    return arena, param


def run(exe, t_input):
    inputs_file = exe.parent / "inputs.bin"
    X = pad(globals()["X"], exe.parent.name)
    if t_input == "int8_t":   # Aidge export convention: inputs in [-1, 1], x 127
        assert np.abs(X).max() <= 1, "input outside [-1, 1]: clipping would distort the quantization"
        np.clip(np.round(X * 127), -128, 127).astype(np.int8).tofile(inputs_file)
    else:
        X.tofile(inputs_file)
    r = subprocess.run([str(exe), str(inputs_file), str(len(X)), str(exe.parent / "outputs.txt")],
                       capture_output=True, text=True, timeout=600)
    if r.returncode != 0:
        return None, None, r.returncode
    med, p95 = map(float, r.stdout.split())
    return np.loadtxt(exe.parent / "outputs.txt"), (med, p95), 0


FILTER = sys.argv[1:]          # configuration names: partial run, summary not rewritten
reports, outputs = [], {}
for name, onnx, dtype, dformat, note, *options in CONFIGS:
    if FILTER and name not in FILTER and name != "cnn1d_f32_ncw":   # float reference always useful
        continue
    b = dict(config=name, onnx=onnx.name, dtype=dtype, dformat=dformat or "auto", note=note)
    try:
        folder, b["quantizable"] = generate(name, onnx, dtype, dformat, options[0] if options else None)
        exe, t_input = compile_harness(folder)
        b["input_type"] = t_input
        b["arena_bytes"], b["params_bytes"] = memory(folder)
        s, lat, code = run(exe, t_input)
        b["return_code"] = code
        if s is not None:
            outputs[name] = s
            b["latency_ms"], b["latency_p95_ms"] = lat
    except Exception as e:
        b["error"] = f"{type(e).__name__}: {str(e)[:300]}"
    reports.append(b)
    print(name, {k: v for k, v in b.items() if k not in ("onnx", "note")}, flush=True)

# --- Comparisons -------------------------------------------------------------
y = D["y_test"]
ref = {"cnn": D["ort_cnn_folded"], "pca": D["ort_pca_f32"], "pca_nc": D["ort_pca_nc"],
       "pca_nc_q8": D["ort_pca_nc_q8"]}
for b in reports:
    s = outputs.get(b["config"])
    if s is None:
        continue
    fam = b["config"][:3]
    st, sc = s[:NT], s[NT:]
    b["auc_64"] = float(roc_auc_score(y, st))
    b["auc_64_onnxruntime"] = float(roc_auc_score(y, ref[fam]))
    if fam == "cnn":
        # output not dequantized (int8): factor alpha estimated on the calibration set against the C++ float
        f_calib = outputs["cnn1d_f32_ncw"][NT:]
        alpha = float(np.dot(sc, f_calib) / np.dot(f_calib, f_calib))
        b["alpha"] = alpha
        b["max_diff_vs_ort"] = float(np.abs(st / alpha - ref["cnn"]).max())
        b["decision_agreement"] = float(((st > 0) == (ref["cnn"] > 0)).mean())
        b["correlation"] = float(np.corrcoef(st, ref["cnn"])[0, 1])
    else:
        r = ref["pca_nc_q8" if "nc_int8_weights" in b["config"] else "pca_nc" if "_nc_" in b["config"] else "pca"]
        b["max_rel_diff_vs_ort"] = float(np.abs(st / r - 1).max())
        b["correlation"] = float(np.corrcoef(st, r)[0, 1])

if not FILTER:
    (OUT / "measurements.json").write_text(json.dumps(reports, ensure_ascii=False, indent=1))

L = ["# Step 5: C++ export with Eclipse Aidge 0.10.1", "",
     "Generated by `step05_aidge_export/export_aidge.py`. 64 test measurements (32 healthy, 32 damaged, fold "
     "position_D04, CNN model seed 0; \"position\" PCA). Latency: C++ harness compiled "
     "`-O3 -ffast-math -march=native`, 1 thread, batch of 1, median over 1000 inferences "
     "(workstation processor: relative orders of magnitude).", "",
     "Fidelity: relative to ONNX Runtime on the same float graph (CNN: int8 output divided by α, "
     "factor estimated on the calibration set). AUC (64): ONNX Runtime float gives 1.000 (CNN) and 0.970 (PCA "
     "without quality check: 2 of the 64 measurements have an empty path).", "",
     "| configuration | result | input | parameters | compute arena | latency | fidelity | AUC (64) |",
     "|---|---|---|---|---|---|---|---|"]
for b in reports:
    if "error" in b:
        res = f"export failure: {b['error'][:90]}"
    elif b.get("return_code"):
        res = f"compiles, **crashes at run time** (code {b['return_code']})"
    else:
        res = "runs" + (" (graph not quantizable: only the input is int8)"
                         if b.get("quantizable") is False else "")
    fid = ""
    if "correlation" in b:   # sign agreement is misleading here: the 64 float logits are all negative
        fid = (f"correlation {b['correlation']:.3f}, max diff {b['max_diff_vs_ort']:.2g}" if "alpha" in b
               else f"correlation {b['correlation']:.4f}, max relative diff {b['max_rel_diff_vs_ort']:.1e}")
    L.append(f"| {b['config']} | {res} | {b.get('input_type', '')} "
             f"| {b.get('params_bytes', 0) / 1024:.0f} KB | {b.get('arena_bytes', 0) / 1024:.0f} KB "
             f"| {b.get('latency_ms', float('nan')):.3f} ms | {fid} | {b.get('auc_64', float('nan')):.3f} |")
if not FILTER:
    (OUT / "summary.md").write_text("\n".join(L) + "\n")
print("\n".join(L))
