"""Step 10: deep autoencoders versus PCA (40 kHz), same protocol as Step 3.

- training on the heating ramp of healthy cycle 1, validation (early stopping, healthy
  levels, threshold) on its cooling ramp; no damaged measurement in training;
- latent space chosen per fold on the validation set (healthy measurements of the cooling ramp
  + positions outside the test set): smallest latent reaching the best AUC, seed 0;
- 3 seeds for the selected latent; test set opened once.
Run (from the repository root, with PYTHONPATH=src): python step10_autoencoders/autoencoders.py
"""
import json
from multiprocessing import Pool
from pathlib import Path

import numpy as np
import torch
from sklearn.metrics import roc_auc_score

from ogw.autoencoder import AEConv, AEDense, AEDetector
from ogw.splits import POSITIONS, by_temperature, position_folds
from ogw.data import load_meta, load_signals
from ogw.models import n_mac

OUT = Path(__file__).resolve().parents[1] / "results" / "step10_autoencoders"
ARCHS = {"AEConv": AEConv, "AEDense": AEDense}
LATENTS = (2, 5, 10)
SEEDS = (0, 1, 2)


def _train(task):
    torch.set_num_threads(4)
    arch, latent, seed, key = task
    meta, X = load_meta(), load_signals()
    if key == "position":
        s1 = (meta.damaged == 0) & (meta.cycle == 1)
        e, v = np.flatnonzero(s1 & (meta.ramp == 0)), np.flatnonzero(s1 & (meta.ramp == 1))
    else:
        d = by_temperature(meta)
        e = d.train[meta.damaged[d.train] == 0]
        v = d.validation[meta.damaged[d.validation] == 0]
    det = AEDetector(ARCHS[arch], latent, seed).fit(X, e, v)
    return (arch, latent, seed, key), det.scores(np.arange(len(meta))), dict(
        threshold=float(det.threshold), healthy_val_scores=det.healthy_val_scores.tolist(), val=v.tolist(),
        epoch=det.best_epoch, val_loss=det.val_loss, n_params=det.n_parameters(),
        mac=int(n_mac(det.model, X.shape[1:])) if arch == "AEConv" else det.n_parameters())


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    tasks = [(a, l, g, c) for a in ARCHS for l in LATENTS for g in SEEDS for c in ("position", "temperature")]
    with Pool(len(tasks)) as pool:
        res = {k: (s, info) for k, s, info in pool.map(_train, tasks)}
    meta = load_meta()
    lines, reports = [], []
    for a in ARCHS:
        for d in [*position_folds(meta), by_temperature(meta)]:
            key = "temperature" if d.name == "temperature" else "position"
            if key == "position":
                p = d.name.removeprefix("position_")
                vd = np.flatnonzero((meta.damaged == 1) & (meta.position != p))
                aucs = {}
                for l in LATENTS:
                    s, info = res[(a, l, 0, key)]
                    vs = np.array(info["val"])
                    aucs[l] = roc_auc_score(np.r_[np.zeros(len(vs)), np.ones(len(vd))], np.r_[s[vs], s[vd]])
                l = min(x for x in LATENTS if aucs[x] == max(aucs.values()))
            else:   # latent most often selected on the position folds
                ls = [b["latent"] for b in reports if b["arch"] == a]
                l = max(set(ls), key=ls.count)
                aucs = {}
            y = d.target[d.test]
            per_seed = []
            for g in SEEDS:
                s, info = res[(a, l, g, key)]
                st = s[d.test]
                per_seed.append(dict(auc=roc_auc_score(y, st), fpr=float((st[y == 0] > info["threshold"]).mean()),
                                     tpr=float((st[y == 1] > info["threshold"]).mean())))
            info = res[(a, l, 0, key)][1]
            reports.append(dict(arch=a, split=d.name, latent=l, aucs_val=aucs, seeds=per_seed,
                                n_params=info["n_params"], mac=info["mac"], epoch=info["epoch"]))
    (OUT / "measurements.json").write_text(json.dumps(reports, ensure_ascii=False))
    pca = {b["split"]: b for b in json.loads((OUT.parent / "step03_cnn_vs_pca" / "pca_test.json").read_text())}
    L = ["# Step 10: deep autoencoders versus PCA (40 kHz)", "",
         "Generated by `step10_autoencoders/autoencoders.py`. Training on 79 healthy measurements; latent chosen per fold "
         "on the validation set; 3 seeds.", "",
         "| split | PCA k = 5 (Step 3) | AEConv: latent, AUC (mean ± std), FPR | AEDense: latent, AUC, FPR |",
         "|---|---|---|---|"]
    for n in ["position_D04", "position_D12", "position_D16", "position_D24", "temperature"]:
        cell = []
        for a in ARCHS:
            b = [x for x in reports if x["arch"] == a and x["split"] == n][0]
            au = np.array([g["auc"] for g in b["seeds"]])
            cell.append(f"{b['latent']}, {au.mean():.3f} ± {au.std():.3f}, {np.mean([g['fpr'] for g in b['seeds']]):.1%}")
        L.append(f"| {n} | {pca[n]['auc_test']:.3f}, FPR {pca[n]['fpr_threshold']:.1%} | " + " | ".join(cell) + " |")
    L += ["", "| model | parameters | float32 memory | multiply-accumulates |", "|---|---|---|---|"]
    for a in ARCHS:
        b = [x for x in reports if x["arch"] == a][0]
        L.append(f"| {a} (latent {b['latent']}) | {b['n_params']:,} | {b['n_params'] * 4 / 1e6:.2f} MB "
                 f"| {b['mac'] / 1e6:.2f} M |")
    L.append(f"| PCA k = 5 (Step 3) | 324,852 | 1.30 MB | 0.54 M |")
    (OUT / "summary.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))
