"""Step 1: exploration of the OGW data (selected frequency: 40 kHz).

Produces the figures in results/step01_exploration/ and the figures quoted in
results/step01_exploration/summary.md.
Run (from the repository root): PYTHONPATH=src python step01_exploration/exploration.py

Central measure: the relative residual R(a, b) = ||a - b||² / ||b||², path by
path, between a measurement a and a healthy baseline b. The residual caused by
the damage is compared with the one separating two healthy measurements taken
on different days (cycle 2 against cycle 1), for three ways of choosing the
baseline b.
"""
from pathlib import Path

import h5py
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch

from ogw.data import Q, load_meta, load_signals, ogw_file
from ogw.splits import POSITIONS, by_temperature, check, drift_control, position_folds, summary

OUT = Path(__file__).resolve().parents[1] / "results" / "step01_exploration"
OUT.mkdir(parents=True, exist_ok=True)

meta = load_meta()
F = meta.f_kHz * 1e3
X = load_signals().astype(np.float64)             # (966, 66, L), centred, decimated, filtered
fs = meta.fs / Q
t_us = np.arange(X.shape[-1]) / fs * 1e6
healthy1 = np.flatnonzero((meta.damaged == 0) & (meta.cycle == 1))
healthy2 = np.flatnonzero((meta.damaged == 0) & (meta.cycle == 2))
lines = [f"# Step 1: exploration figures at {meta.f_kHz} kHz", "",
         "Generated by `step01_exploration/exploration.py`. Signals centred, decimated "
         f"(q = {Q}, {fs / 1e3:.0f} kHz, {X.shape[-1]} points), band-pass filtered "
         f"[{meta.f_kHz / 2:.0f}, {2 * meta.f_kHz:.0f}] kHz.", ""]


def name(k):
    return f"{meta.paths[k][0]}-{meta.paths[k][1]}"


def residual(a, b):
    """Relative residual per path; a and b of shape (..., 66, L)."""
    return ((a - b) ** 2).sum(-1) / (b ** 2).sum(-1)


# --- 1. Timeline and temperature ---------------------------------------------
fig, ax = plt.subplots(1, 2, figsize=(12, 3.6))
days = meta.date - meta.date.min()
groups = [("udam", 1, "k", "healthy c1"), ("udam", 2, "0.5", "healthy c2"), ("dam_D12", 1, "C0", "D12"),
          ("dam_D16", 1, "C1", "D16"), ("dam_D04", 1, "C2", "D04"), ("dam_D24", 1, "C3", "D24")]
lines += ["## Setpoint and measured temperature", "",
          "| campaign | measured T minus setpoint (mean) | min | max |", "|---|---|---|---|"]
for lab, c, col, leg in groups:
    m = (meta.label == lab) & (meta.cycle == c)
    offset_T = meta.T_measured[m] - meta.T_setpoint[m]
    ax[0].plot(days[m], meta.T_measured[m], ".", ms=3, color=col, label=leg)
    ax[1].plot(meta.T_setpoint[m], offset_T, ".", ms=3, color=col, label=leg)
    lines.append(f"| {leg} | {offset_T.mean():+.2f} °C | {offset_T.min():+.2f} | {offset_T.max():+.2f} |")
ax[0].set_xlabel("days since the first measurement"); ax[0].set_ylabel("measured T (°C)")
ax[0].set_title("All healthy measurements precede the damaged ones")
ax[1].set_xlabel("setpoint (°C)"); ax[1].set_ylabel("measured T minus setpoint (°C)")
ax[1].set_title("The setpoint/plate offset depends on the campaign")
ax[0].legend(ncol=3, fontsize=7)
fig.tight_layout(); fig.savefig(OUT / "01_temperature_timeline.png", dpi=110); plt.close(fig)

# --- 2. Raw and preprocessed signal; 3. spectrum -----------------------------
PATH = 0
with h5py.File(ogw_file(), "r") as f:
    raw = f["catch"][healthy1[0], PATH].astype(np.float64)
    raw40 = f["catch"][healthy1[:40]].astype(np.float64)
t_raw = np.arange(raw.size) / meta.fs * 1e6
emission = 5 / F * 1e6                              # excitation duration (5 cycles)
fig, ax = plt.subplots(2, 1, figsize=(9, 5))
for a, lim in zip(ax, [None, (0, 3 * emission)]):
    a.plot(t_raw, raw, lw=0.6, label="raw (10 MHz)")
    a.plot(t_us, X[healthy1[0], PATH], lw=0.9, label=f"preprocessed ({fs / 1e3:.0f} kHz)")
    a.axvspan(0, emission, color="0.9", zorder=0)
    if lim:
        a.set_xlim(lim)
    a.set_xlabel("t (µs)")
ax[0].legend(fontsize=8)
ax[0].set_title(f"Path {name(PATH)}, healthy: DC offset of the raw signal, removed by preprocessing")
ax[1].set_title(f"Zoom: emission (grey area, {emission:.0f} µs) and electrical crosstalk")
fig.tight_layout(); fig.savefig(OUT / "02_typical_signal.png", dpi=110); plt.close(fig)

offset = raw40.mean(-1)
lines += ["", "## Raw signal", "",
          f"- DC offset: {np.abs(offset).mean() / raw40.std(-1).mean():.0%} of the RMS on average (40 measurements)."]
raw40 -= raw40.mean(-1, keepdims=True)
E = (np.abs(np.fft.rfft(raw40, axis=-1)) ** 2).sum((0, 1))
fr = np.fft.rfftfreq(raw40.shape[-1], 1 / meta.fs)
cum = np.cumsum(E) / E.sum()
in_band = cum[np.searchsorted(fr, 2 * F)] - cum[np.searchsorted(fr, F / 2)]
lines += [f"- Energy (centred signal) in the band [{F / 2e3:.0f}, {2 * F / 1e3:.0f}] kHz: {in_band:.2%}; "
          f"below {F / 2e3:.0f} kHz: {cum[np.searchsorted(fr, F / 2)]:.2%}; "
          f"above {fs / 2e3:.0f} kHz (Nyquist after decimation): {1 - cum[np.searchsorted(fr, fs / 2)]:.2%}."]
fig, ax = plt.subplots(figsize=(8, 3.5))
ax.semilogy(fr / 1e3, E / E.max(), lw=0.7)
ax.axvspan(F / 2e3, 2 * F / 1e3, color="C2", alpha=0.15, label="retained band")
ax.axvline(fs / 2e3, color="C3", ls="--", label=f"{fs / 2e3:.0f} kHz (Nyquist after decimation)")
ax.set_xlim(0, 1000); ax.set_ylim(1e-8, 2); ax.set_xlabel("f (kHz)")
ax.set_title("Mean energy spectrum (centred raw signals)"); ax.legend(fontsize=8)
fig.tight_layout(); fig.savefig(OUT / "03_spectrum.png", dpi=110); plt.close(fig)

# --- 4. Temperature effect ---------------------------------------------------
TR = 30
fig, ax = plt.subplots(2, 1, figsize=(9, 5))
for T in (22.0, 40.0, 60.0):
    i = healthy1[np.argmin(np.abs(meta.T_measured[healthy1] - T))]
    for a in ax:
        a.plot(t_us, X[i, TR], lw=0.8, label=f"{meta.T_measured[i]:.1f} °C")
ZOOM = (280, 400)
win = (t_us >= ZOOM[0]) & (t_us <= ZOOM[1])
ymax = max(np.abs(l.get_ydata()[win]).max() for l in ax[1].lines)
ax[1].set_xlim(ZOOM); ax[1].set_ylim(-1.1 * ymax, 1.1 * ymax)
ax[0].set_title(f"Path {name(TR)}, healthy: temperature shifts and distorts the arrivals")
ax[1].set_title("Zoom: a few µs of delay between 22 and 60 °C, far more than the damage effect"); ax[1].set_xlabel("t (µs)")
ax[0].legend(fontsize=8)
fig.tight_layout(); fig.savefig(OUT / "04_temperature_effect.png", dpi=110); plt.close(fig)

# --- 5. Damage against healthy variability, depending on the baseline choice ---
def baseline_setpoint(i):
    return healthy1[np.argmin(np.abs(meta.T_setpoint[healthy1] - meta.T_setpoint[i]))]


def baseline_measured(i):
    return healthy1[np.argmin(np.abs(meta.T_measured[healthy1] - meta.T_measured[i]))]


Xt = torch.from_numpy(X.reshape(len(meta), -1))
nearest = healthy1[torch.cdist(Xt, Xt[healthy1]).argmin(1).numpy()]   # minimal residual baseline


def baseline_optimal(i):
    return nearest[i]


strategies = {"chamber setpoint": baseline_setpoint, "measured temperature": baseline_measured,
              "optimal baseline (minimal residual)": baseline_optimal}
compare_groups = {"c2": healthy2, **{p: np.flatnonzero(meta.position == p) for p in POSITIONS}}
lines += ["", "## Damage against healthy variability, depending on the baseline choice", "",
          "Baseline taken from healthy cycle 1. Median relative residual over the measurements, then "
          "median over the 66 paths; \"ratio\" = damage residual / healthy cycle 2 residual, "
          "path by path.", "",
          "| baseline | c2 (no damage) | " + " | ".join(POSITIONS)
          + " | median ratio | max ratio (path) |", "|---" * 8 + "|"]
med = {}
for s_name, ref in strategies.items():
    r = {g: np.median(np.stack([residual(X[i], X[ref(i)]) for i in idx]), 0)
         for g, idx in compare_groups.items()}
    ratio = np.stack([r[p] / r["c2"] for p in POSITIONS])       # (4, 66)
    med[s_name] = (r, ratio)
    kmax = np.unravel_index(ratio.argmax(), ratio.shape)
    lines.append(f"| {s_name} | {np.median(r['c2']):.4f} | "
                 + " | ".join(f"{np.median(r[p]):.4f}" for p in POSITIONS)
                 + f" | {np.median(ratio):.2f} | {ratio.max():.1f} ({POSITIONS[kmax[0]]}, {name(kmax[1])}) |")

# Floor: two healthy measurements of the same cycle 0.5 °C apart
pairs = [(i, healthy1[np.argmin(np.abs(meta.T_measured[healthy1] - meta.T_measured[i] - 0.5))]) for i in healthy1
         if meta.T_measured[i] + 0.5 <= meta.T_measured[healthy1].max()]
floor = np.median(np.stack([residual(X[i], X[j]) for i, j in pairs]), 0)
lines.append(f"\nFloor (healthy c1 against healthy c1, 0.5 °C apart): {np.median(floor):.4f}.")

DT = [0.5, 1.0, 2.0, 5.0, 10.0]
res_T = []
for dT in DT:
    pp = [(i, healthy1[np.argmin(np.abs(meta.T_measured[healthy1] - meta.T_measured[i] - dT))]) for i in healthy1
          if meta.T_measured[i] + dT <= meta.T_measured[healthy1].max()]
    res_T.append(np.median(np.stack([residual(X[i], X[j]) for i, j in pp])))
lines += ["", "Median residual between two healthy cycle 1 measurements as a function of the temperature difference:", "",
          "| difference (°C) | " + " | ".join(map(str, DT)) + " |", "|---" * (len(DT) + 1) + "|",
          "| residual | " + " | ".join(f"{v:.4f}" for v in res_T) + " |"]

fig, ax = plt.subplots(figsize=(8, 4))
ax.plot(DT, res_T, "ko-", label="healthy c1: temperature difference (median over paths)")
colors = {"chamber setpoint": "C3", "measured temperature": "C1",
          "optimal baseline (minimal residual)": "C2"}
for s_name, (r, _) in med.items():
    ax.axhline(np.median(r["c2"]), color=colors[s_name], ls=":", label=f"healthy c2, {s_name}")
    ax.axhline(np.median(np.stack([r[p] for p in POSITIONS])), color=colors[s_name], ls="--",
               label=f"damage, {s_name}")
ax.set_xscale("log"); ax.set_yscale("log"); ax.set_xlabel("temperature difference (°C)")
ax.set_ylabel("relative residual"); ax.legend(fontsize=6.5)
ax.set_title("The baseline choice decides whether the damage is visible")
fig.tight_layout(); fig.savefig(OUT / "05_baseline_and_damage.png", dpi=110); plt.close(fig)

# --- 6. Which paths see the damage? (optimal baseline) -----------------------
_, ratio = med["optimal baseline (minimal residual)"]
fig, ax = plt.subplots(figsize=(11, 2.8))
im = ax.imshow(np.log10(ratio), aspect="auto", cmap="magma")
ax.set_yticks(range(4), POSITIONS); ax.set_xlabel("path index (0 to 65)")
fig.colorbar(im, label="log10(damage residual / c2 residual)")
ax.set_title("Damage sensitivity per path (optimal baseline)")
fig.tight_layout(); fig.savefig(OUT / "06_path_sensitivity.png", dpi=110); plt.close(fig)
lines += ["", "## Sensitive paths (optimal baseline, damage / c2 ratio)", ""]
for p, s in zip(POSITIONS, ratio):
    top = np.argsort(s)[::-1][:5]
    lines.append(f"- {p}: {int((s > 2).sum())} paths above 2; most sensitive "
                 + ", ".join(f"{name(k)} ×{s[k]:.1f}" for k in top))

# --- 7. Amplitude per path (justifies a per-path scale) ----------------------
sd = X[healthy1].std(axis=(0, 2))
lines += ["", f"- Standard deviation per path (healthy c1): from {sd.min():.4f} to {sd.max():.4f}, "
          f"ratio {sd.max() / sd.min():.1f}."]

# --- 8. Splits ---------------------------------------------------------------
lines += ["", "## Splits (number of measurements)", ""]
for d in [*position_folds(meta), by_temperature(meta), drift_control(meta)]:
    check(d, meta)
    lines += [summary(d, meta), ""]

(OUT / "summary.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))
